services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'

  Markocupic\ContaoHeroimageBundle\:
    resource: ../src/
    exclude: ../src/{DependencyInjection}
